version: '3.8'
services:

  wot_generator:
    container_name: wot_generator
    build: .
    restart: always
    ports:
      - 5000:5000
    expose:
      - "5000"

  app:
    build: ./docker
    image: apache_server
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www

  db:
    image: mysql:8
    ports:
      - '3308:3306' 
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_of_things
      MYSQL_USER: wot_user
      MYSQL_PASSWORD: web_of_things_mysql_db@

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'db:db'
    ports:
      - 8002:80

  iot-agent:
    image: fiware/iotagent-json
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
        - mongodb
    expose:
        - "4041"
        - "7896"
    ports:
        - "4041:4041"
        - "7896:7896"
    environment:
        - "IOTA_CB_HOST=orion"
        - "IOTA_CB_PORT=1026"
        - "IOTA_NORTH_PORT=4041"
        - "IOTA_REGISTRY_TYPE=mongodb"
        - "IOTA_MONGO_HOST=mongodb"
        - "IOTA_MONGO_PORT=27017"
        - "IOTA_MONGO_DB=iotagent-json"
        - "IOTA_HTTP_PORT=7896"
        - "IOTA_PROVIDER_URL=http://iot-agent:4041"

  mongodb:
    image: mongo:4.2
    hostname: mongodb
    container_name: db-mongo
    ports:
      - "27017:27017"
    command: --bind_ip_all
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  orion:
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongodb
    ports:
      - "1026:1026"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/iotagent-json
      - ORION_LOG_LEVEL=DEBUG
    restart: on-failure

  
volumes:
  mysql-data:
  mongodb: