version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INSIDE:INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_ORIGIN: INSIDE
      KAFKA_LISTENER_SSL_CLIENT_AUTH: NONE
      KAFKA_LISTENER_EXPOSED_CLIENT_AUTH: NONE

  python-app:
    build:
      context: .
    depends_on:
      - kafka
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "./wait-for-kafka.sh && python main.py"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9093  # Ensure this points to the internal Kafka address and port
    depends_on:
      - kafka
    volumes:
      - ./wait-for-kafka.sh:/wait-for-kafka.sh
    command: /bin/bash -c "./wait-for-kafka.sh && java -jar /app/kafdrop.jar"